apiVersion: v1
kind: Service
metadata:
  name: ozan-cakar-service
  namespace: default
spec:
  selector:
    app: ozan-cakar
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer

